site_name: "ChocoLogParse PowerShell Module"
site_url: https://heyitsgilbert.github.io/ChocoLogParse/
repo_url: https://github.com/HeyItsGilbert/ChocoLogParse
theme: readthedocs
nav:
  - Home: 'index.md'
  - Changelog: 'https://github.com/HeyItsGilbert/ChocoLogParse/blob/main/CHANGELOG.md'
  - en-US:
      - en-US/
plugins:
  - search
  - include_dir_to_nav
