name: reviewdog-suggester
on: [pull_request] # Support only pull_request event.
jobs:
  shell:
    name: runner / suggester / shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4.2.2
      - shell: pwsh
        run: Invoke-ScriptAnalyzer . -Fix
      - name: suggester / psscriptanalyzer
        uses: reviewdog/action-suggester@4747dbc9f9e37adba0943e681cc20db466642158 # v1.21.0
        with:
          tool_name: 'PSScriptAnalyzer'
